#!/usr/bin/env python3

'''
Script to run authentication user
'''

import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

# Define command to publish map
_COMMAND_ = './delete_client.py --Ice.Config=room_tool.config "%(auth_proxy)s" %(token)s "%(map)s"'

# Message used by authentication client when asking for a password
_PASSWORD_MESSAGE_ = 'Introduce la contrasena: '
_TIMEOUT_FOR_MESSAGE_ = 15

# Get required arguments
try:
    proxy, token, _map_ = sys.argv[1:]
except ValueError:
    print('Command arguments: {} <proxy> <token> <map>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'auth_proxy': proxy,
    'token': token,
    'map' : _map_
}

# Run command
proc = pexpect.spawn(final_command, echo=False)


# Show command output and exit
#print(proc.before.decode().strip())
#sys.exit(0)
